
server:
    port: 9527

spring:
    application:
        name: cloud-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true #???????????????????????????
            routes:
                - id: payment_routh #payment_route    #???ID????????????????????
                    #uri: http://localhost:8001          #????????????
                  uri: lb://cloud-payment-service #????????????
                  predicates:
                      - Path=/payment/get/**         # ?????????????

                - id: payment_routh2 #payment_route    #???ID????????????????????
                    #uri: http://localhost:8001          #????????????
                  uri: lb://cloud-payment-service #????????????
                  predicates:
                      - Path=/payment/lb/**         # ?????????????
                      #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
                      #- Cookie=username,zzyy
                      #- Header=X-Request-Id, \d+  # ?????X-Request-Id??????????????

eureka:
    instance:
        hostname: cloud-gateway-service
    client: #?????provider???eureka?????
        service-url:
            register-with-eureka: true
            fetch-registry: true
            defaultZone: http://eureka7001.com:7001/eureka


